package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Convert", targetNamespace = "http://ws/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Convert {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/inchesToFeetDRequest", output = "http://ws/Convert/inchesToFeetDResponse")
    public static double inchesToFeetD(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/feetToInchesDRequest", output = "http://ws/Convert/feetToInchesDResponse")
    public static double feetToInchesD(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/feetToInchesRequest", output = "http://ws/Convert/feetToInchesResponse")
    public static double feetToInches(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/inchesToCentiDRequest", output = "http://ws/Convert/inchesToCentiDResponse")
    public static double inchesToCentiD(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/inchesToFeetRequest", output = "http://ws/Convert/inchesToFeetResponse")
    public static double inchesToFeet(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/centiToInchesRequest", output = "http://ws/Convert/centiToInchesResponse")
    public static double centiToInches(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/inchesToCentiRequest", output = "http://ws/Convert/inchesToCentiResponse")
    public static double inchesToCenti(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/milesToKilometersRequest", output = "http://ws/Convert/milesToKilometersResponse")
    public static double milesToKilometers(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/kilometersToMilesDRequest", output = "http://ws/Convert/kilometersToMilesDResponse")
    public static double kilometersToMilesD(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/kilometersToMilesRequest", output = "http://ws/Convert/kilometersToMilesResponse")
    public static double kilometersToMiles(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/milesToKilometersDRequest", output = "http://ws/Convert/milesToKilometersDResponse")
    public static double milesToKilometersD(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/daysToMonthsRequest", output = "http://ws/Convert/daysToMonthsResponse")
    public static double daysToMonths(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/feetToMilesDRequest", output = "http://ws/Convert/feetToMilesDResponse")
    public static double feetToMilesD(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/daysToMonthsDRequest", output = "http://ws/Convert/daysToMonthsDResponse")
    public static double daysToMonthsD(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/feetToMilesRequest", output = "http://ws/Convert/feetToMilesResponse")
    public static double feetToMiles(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/weeksToYearsDRequest", output = "http://ws/Convert/weeksToYearsDResponse")
    public static double weeksToYearsD(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/milesToFeetRequest", output = "http://ws/Convert/milesToFeetResponse")
    public static double milesToFeet(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/milesToFeetDRequest", output = "http://ws/Convert/milesToFeetDResponse")
    public static double milesToFeetD(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/weeksToYearsRequest", output = "http://ws/Convert/weeksToYearsResponse")
    public static double weeksToYears(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/monthsToDaysRequest", output = "http://ws/Convert/monthsToDaysResponse")
    public static double monthsToDays(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/yearsToWeeksRequest", output = "http://ws/Convert/yearsToWeeksResponse")
    public static double yearsToWeeks(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/yearsToWeeksDRequest", output = "http://ws/Convert/yearsToWeeksDResponse")
    public static double yearsToWeeksD(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/centiToInchesDRequest", output = "http://ws/Convert/centiToInchesDResponse")
    public static double centiToInchesD(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws/Convert/monthsToDaysDRequest", output = "http://ws/Convert/monthsToDaysDResponse")
    public static double monthsToDaysD(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

}
